services:
  dev:
    environment:
      WEB_BASIC_USER: USER
      WEB_BASIC_PW: PASSWORD
    volumes:
      - type: bind
        source: ../../test_data
        target: /test_data

  postgres:
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
    
  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: PASSWORD
